### ISSUE TITLE
Minor resolution bug

### ISSUE THREAD

**Issue by RedBaronFel** [casey-c/infomod2#3]
I play at 1920 by 1200 and the hover tooltips on all the things top right are all down to far, probably by the 120 pixels between 1080 and 1200 lol.
![image](https://user-images.githubusercontent.com/44959740/114455709-a8dc9380-9ba1-11eb-82b4-e1ab76d8bcec.png)

**Comment by casey-c** [comment]
Hi - thanks for the feedback! Just confirming: all the main tool tips have this issue [e.g. shop tip, potion, etc.]? I can take another look at this for the next update. (What I'm doing right now is an attempt to offset them from the top of the screen down a certain number of pixels - it looks like this hardcoded number of pixels is too low for the tooltip for this taller resolution)

Another question for you - the regular tool tips that were in the base game render in the correct, higher position right? I can't test anything taller than 1920x1080 since that's my monitor's max, so a confirmation here will be helpful so I can know if I can try and decipher what the base game uses and follow that instead. Thanks!

**Comment by RedBaronFel** [comment]
Yes on both counts, all the new tooltips are low and the regular ones render in the correct places.

**Comment by casey-c** [comment]
Good to know - thank you for confirming. I'll dive a bit further into what the base game is doing to try and copy their code to make it work better. I'll try and patch this issue for 0.0.7

**Comment by RedBaronFel** [comment]
Awesome, only just switched to the new version of the mod, looking really good so far, thanks!

**Comment by casey-c** [comment]
Some minor updates to this issue:  I've decided to table the main fix until I port the code into my new easel library (which is coming hopefully by the end of the year, but no promises there). The new library will handle much of the rendering, so I just will make sure the offsets are correct since I'll basically be "redoing" it all then. So, I'm going to close this issue for now but definitely will keep it in mind for the major easel port update.
